import { Language, SiteSettings } from './types';

export const DEFAULT_SETTINGS: SiteSettings = {
  branding: {
    siteNameAr: 'الجامعة الأمريكية المفتوحة',
    siteNameEn: 'American Open University',
    footerText: 'AOU 1995 © All Rights Reserved',
    announcements: [],
    logo: '/assets/logo.png'
  },
  theme: {
    primary: '#1e3a8a',
    secondary: '#3b82f6',
    accent: '#f59e0b',
    background: '#f8fafc',
    cardBg: '#ffffff',
    textPrimary: '#1e293b',
    textSecondary: '#64748b',
    borderColor: '#e2e8f0'
  },
  darkTheme: {
    primary: '#636363',      // Matte Gray Primary
    secondary: '#636363',    // Matte Gray Secondary
    accent: '#636363',       // Matte Gray Accent
    background: '#7C7979',   // Matte Gray Background
    cardBg: '#999999',       // Matte Gray Card Background
    textPrimary: '#000000',  // Pure Black for Contrast
    textSecondary: '#000000',// Pure Black for Contrast
    borderColor: '#5e5e5e'   // Darker shade for borders
  },
  fonts: {
    arabicFont: 'Tajawal',
    latinFont: 'Inter',
    baseFontSize: '16px'
  },
  registrationStatus: 'open',
  isDarkMode: false,
  defaultSemesterId: undefined
};

export const TRANSLATIONS: Record<Language, any> = {
  AR: {
    dir: 'rtl',
    regionalCenter: 'المركز الإقليمي الأول',
    login: 'تسجيل الدخول',
    signup: 'إنشاء حساب',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    fullName: 'الاسم الكامل',
    universityId: 'الرقم الجامعي',
    phone: 'رقم الهاتف',
    major: 'التخصص',
    nationality: 'الجنسية',
    passportNumber: 'رقم جواز السفر',
    dateOfBirth: 'تاريخ الميلاد',
    dobDay: 'يوم',
    dobMonth: 'شهر',
    dobYear: 'سنة',
    ageError: 'يجب أن يكون العمر 18 سنة على الأقل لإنشاء حساب',
    selectNationality: 'اختر الجنسية',
    logout: 'تسجيل الخروج',
    dashboard: 'لوحة التحكم',
    registration: 'التسجيل',
    myCourses: 'موادي',
    myTimetable: 'جدولي الدراسي',
    profile: 'الملف الشخصي',
    courses: 'المواد الدراسية',
    students: 'الطلاب',
    enrollments: 'التسجيلات',
    export: 'تصدير البيانات',
    settings: 'إعدادات الموقع',
    save: 'حفظ',
    applyChanges: 'تطبيق التغييرات',
    resetChanges: 'إعادة تعيين',
    cancel: 'إلغاء',
    addCourse: 'إضافة مادة',
    editCourse: 'تعديل مادة',
    courseCode: 'رمز المادة',
    courseTitle: 'اسم المادة',
    credits: 'الساعات',
    register: 'تسجيل',
    unregister: 'حذف',
    enrolled: 'مسجل',
    search: 'بحث...',
    noData: 'لا توجد بيانات',
    welcome: 'أهلاً بك',
    adminPanel: 'لوحة الإدارة',
    studentPanel: 'لوحة الطالب',
    exportExcel: 'تصدير إكسل',
    settingsSubtitle: "لوحة تحكم مباشرة للهوية والألوان",
    changesApplied: "تم تطبيق التغييرات",
    identity: "الهوية",
    visuals: "المظهر",
    siteBranding: "هوية الموقع",
    universityNameArLabel: "اسم الجامعة (عربي)",
    universityNameEnLabel: "اسم الجامعة (إنجليزي)",
    footerTextLabel: "نص الفوتر",
    officialLogo: "الشعار الرسمي",
    uploadNewLogo: "رفع شعار جديد",
    portalPalette: "ألوان البوابة",
    livePreviewCard: "بطاقة معاينة مباشرة",
    previewHeading: "عنوان المعاينة",
    previewText: "هكذا ستظهر مكونات الموقع مع الألوان المختارة.",
    sampleButton: "زر تجريبي",
    registrationControlTitle: "التحكم في التسجيل",
    registrationStatusLabel: "حالة تسجيل المواد",
    registrationOpen: "مفتوح",
    registrationClosed: "مغلق",
    registrationClosedMsg: "نعتذر، تسجيل المواد مغلق حالياً.",
    confirmRegistration: "تأكيد التسجيل",
    editRegistration: "تعديل الجدول",
    selectedCourses: "المواد المختارة",
    filterAll: "جميع التسجيلات",
    filterByCourse: "تصفية حسب المادة",
    filterByStudent: "تصفية حسب الطالب",
    selectMajor: "اختر التخصص",
    assignments: "التكاليف",
    grading: "رصد الدرجات",
    addAssignment: "إضافة تكليف",
    editAssignment: "تعديل التكليف",
    assignmentType: "نوع التكليف",
    fileUpload: "إرفاق ملف",
    mcq: "اختيار من متعدد",
    essay: "أسئلة مقالية",
    deadline: "الموعد النهائي",
    questions: "الأسئلة",
    addQuestion: "إضافة سؤال",
    options: "الاختيارات",
    correctAnswer: "الإجابة الصحيحة",
    submit: "تسليم",
    submitted: "تم التسليم",
    notSubmitted: "لم يتم التسليم",
    showResults: "عرض النتائج للطلاب",
    resultsHidden: "النتائج مخفية",
    resultsVisible: "النتائج معروضة",
    grade: "الدرجة",
    manualGrading: "رصد يدوي",
    bulkGrading: "رصد جماعي",
    downloadAll: "تحميل الكل",
    deleteSubmissions: "حذف جميع التسجيلات",
    systemOverview: "نظرة عامة على النظام",
    enrollmentDist: "توزيع الطلاب على المواد",
    recentActivity: "آخر النشاطات",
    darkMode: "الوضع الليلي",
    lightMode: "الوضع النهاري",
    editDarkModePalette: "تعديل ألوان الوضع الليلي",
    editLightModePalette: "تعديل ألوان الوضع النهاري",
    accountDisabledMsg: "حسابك مغلق مؤقتا قم بمراجعة الادارة",
    disable: "تعطيل",
    enable: "تفعيل",
    majorList: {
      islamic_studies: "الدراسات الإسلامية",
      islamic_economics: "الاقتصاد والمصارف الإسلامية",
      business_admin: "إدارة الأعمال",
      media_pr: "الإعلام والعلاقات العامة",
      edu_science: "العلوم التربوية",
      sharia_law: "الشريعة والقانون",
      arabic_lang: "اللغة العربية",
      accounting: "المحاسبة",
      mis: "نظم معلومات إدارية",
      jurisprudence: "الفقه المذهبي",
      english_lang: "اللغة الإنجليزية"
    },
    days: {
      Sunday: "الأحد",
      Monday: "الأثنين",
      Tuesday: "الثلاثاء",
      Wednesday: "الأربعاء",
      Thursday: "الخميس",
      Friday: "الجمعة",
      Saturday: "السبت"
    },
    doctor: "الأستاذ",
    day: "اليوم",
    time: "الوقت",
    courseStatus: "حالة المادة",
    regEnabled: "التسجيل متاح",
    regDisabled: "التسجيل مغلق",
    downloadTimetable: "تحميل الجدول كصورة",
    announcements: "الإعلانات",
    // University ID Registry
    universityIdRegistry: "سجل الأرقام الجامعية",
    registryAccess: "الوصول إلى السجل",
    uploadExcel: "رفع ملف إكسل",
    addManually: "إضافة يدوياً",
    universityIdColumn: "الرقم الجامعي",
    nameColumn: "الاسم",
    statusColumn: "الحالة",
    createdAtColumn: "تاريخ الإضافة",
    usedAtColumn: "تاريخ الاستخدام",
    available: "متاح",
    used: "مستخدم",
    registryFilterAll: "الكل",
    filterAvailable: "المتاحة فقط",
    filterUsed: "المستخدمة فقط",
    searchPlaceholder: "ابحث بالرقم الجامعي...",
    uploadSuccess: "تم رفع الملف بنجاح",
    recordsAdded: "سجلات مضافة",
    recordsSkipped: "سجلات متجاوزة",
    duplicateWarning: "تم تجاوز الأرقام المكررة",
    invalidFormat: "صيغة الملف غير صحيحة. استخدم ملف Excel (.xlsx)",
    exportAll: "تصدير الكل",
    exportAvailable: "تصدير المتاح",
    exportUsed: "تصدير المستخدم",
    idNotRegistered: "الرقم الجامعي غير مسجّل في النظام. يرجى التواصل مع الإدارة.",
    idAlreadyUsed: "الرقم الجامعي مستخدم مسبقًا ولا يمكن إنشاء حساب جديد به.",
    cannotEditUsedId: "لا يمكن تعديل رقم جامعي مستخدم",
    addStudent: "إضافة طالب",
    editStudent: "تعديل بيانات الطالب",
    deleteStudent: "حذف من السجل",
    confirmDelete: "هل أنت متأكد من حذف هذا السجل?",
    totalRecords: "إجمالي السجلات",
    availableRecords: "السجلات المتاحة",
    usedRecords: "السجلات المستخدمة",
    // Exams & Transcript
    exams: "الامتحانات",
    transcript: "السجل الأكاديمي",
    transcripts: "السجلات الأكاديمية",
    examManagement: "إدارة الامتحانات",
    newExam: "امتحان جديد",
    examTitle: "عنوان الامتحان",
    totalMarks: "الدرجة الكلية",
    startsAt: "يبدأ في",
    endsAt: "ينتهي في",
    published: "منشور",
    draft: "مسودة",
    resultsReleased: "نتائج صادرة",
    releaseSemester: "اعتماد الفصل",
    semesterApproval: "اعتماد الفصول الدراسية",
    startExam: "ابدأ الامتحان",
    submitExam: "تسليم الامتحان",
    viewResults: "عرض النتائج",
    pendingResults: "في انتظار النتائج",
    noExams: "لا توجد امتحانات",
    exportPDF: "تحميل PDF",
    cumulativeGPA: "المعدل التراكمي",
    attendance: "الحضور",
    participation: "المشاركة",
    duplicateQuestion: "نسخ السؤال",
    draftSaved: "تم حفظ المسودة",
    saveExam: "حفظ الامتحان",
    exportGrades: "تصدير الدرجات",
    exportAllExams: "تصدير جميع الامتحانات",
    exportThisExam: "تصدير هذا الامتحان",
    studentSearch: "بحث عن طالب",
    examsTaken: "الامتحانات المؤداة",
    score: "الدرجة",
    allFieldsRequired: "جميع الحقول مطلوبة",
    totalMustBe50: "يجب أن يكون المجموع 50",
    confirmDeleteExam: "حذف هذا الامتحان؟",
    confirmSubmitResults: "إصدار النتائج؟ لا يمكن التراجع.",
    examSaved: "تم حفظ الامتحان",
    questionText: "نص السؤال",
    marks: "الدرجة",
    addOption: "إضافة خيار",
    selectCourse: "اختر المادة",
    selectSemester: "اختر الفصل",
    selectStudent: "اختر طالب"
  },
  EN: {
    dir: 'ltr',
    regionalCenter: 'The First Regional Center',
    login: 'Login',
    signup: 'Sign Up',
    email: 'Email',
    password: 'Password',
    fullName: 'Full Name',
    universityId: 'University ID',
    phone: 'Phone Number',
    major: 'Major',
    nationality: 'Nationality',
    passportNumber: 'Passport Number',
    dateOfBirth: 'Date of Birth',
    dobDay: 'Day',
    dobMonth: 'Month',
    dobYear: 'Year',
    ageError: 'You must be at least 18 years old to create an account',
    selectNationality: 'Select Nationality',
    logout: 'Logout',
    dashboard: 'Dashboard',
    registration: 'Registration',
    myCourses: 'My Courses',
    myTimetable: 'My Timetable',
    profile: 'Profile',
    courses: 'Courses',
    students: 'Students',
    enrollments: 'Enrollments',
    export: 'Export Data',
    settings: 'Site Settings',
    save: 'Save',
    applyChanges: 'Apply Changes',
    resetChanges: 'Reset',
    cancel: 'Cancel',
    addCourse: 'Add Course',
    editCourse: 'Edit Course',
    courseCode: 'Course Code',
    courseTitle: 'Course Title',
    credits: 'Credits',
    register: 'Select',
    unregister: 'Remove',
    enrolled: 'Enrolled',
    search: 'Search...',
    noData: 'No data found',
    welcome: 'Welcome',
    adminPanel: 'Admin Panel',
    studentPanel: 'Student Portal',
    exportExcel: 'Export Excel',
    settingsSubtitle: "Live control panel for branding and themes",
    changesApplied: "Changes Applied",
    identity: "Identity",
    visuals: "Visuals",
    siteBranding: "Site Branding",
    universityNameArLabel: "University Name (Arabic)",
    universityNameEnLabel: "University Name (English)",
    footerTextLabel: "Footer Text",
    officialLogo: "Official Logo",
    uploadNewLogo: "Upload New Logo",
    portalPalette: "Portal Palette",
    livePreviewCard: "Live Preview Card",
    previewHeading: "Preview Heading",
    previewText: "This is how your components will appear.",
    sampleButton: "Sample Button",
    registrationControlTitle: "Registration Control",
    registrationStatusLabel: "Course Registration Status",
    registrationOpen: "Open",
    registrationClosed: "Closed",
    registrationClosedMsg: "Course registration is currently closed.",
    confirmRegistration: "Confirm Registration",
    editRegistration: "Edit Selection",
    selectedCourses: "Selected Courses",
    filterAll: "All Enrollments",
    filterByCourse: "Filter by Course",
    filterByStudent: "Filter by Student",
    selectMajor: "Select Major",
    assignments: "Assignments",
    grading: "Grading",
    addAssignment: "Add Assignment",
    editAssignment: "Edit Assignment",
    assignmentType: "Type",
    fileUpload: "File Upload",
    mcq: "Multiple Choice",
    essay: "Essay Questions",
    deadline: "Deadline",
    questions: "Questions",
    addQuestion: "Add Question",
    options: "Options",
    correctAnswer: "Correct Answer",
    submit: "Submit",
    submitted: "Submitted",
    notSubmitted: "Not Submitted",
    showResults: "Show Results to Students",
    resultsHidden: "Results Hidden",
    resultsVisible: "Results Visible",
    grade: "Grade",
    manualGrading: "Manual Grading",
    bulkGrading: "Bulk Grading",
    downloadAll: "Download All",
    deleteSubmissions: "Clear Submissions",
    systemOverview: "System Overview",
    enrollmentDist: "Enrollment Distribution",
    recentActivity: "Recent Activity",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    editDarkModePalette: "Edit Dark Mode Palette",
    editLightModePalette: "Edit Light Mode Palette",
    accountDisabledMsg: "Your account is temporarily closed, please contact management",
    disable: "Disable",
    enable: "Enable",
    majorList: {
      islamic_studies: "Islamic Studies",
      islamic_economics: "Islamic Economics and Banking",
      business_admin: "Business Administration",
      media_pr: "Media and PR",
      edu_science: "Educational Science",
      sharia_law: "Sharia and Law",
      arabic_lang: "Arabic Language",
      accounting: "Accounting",
      mis: "MIS",
      jurisprudence: "Jurisprudence",
      english_lang: "English Language"
    },
    days: {
      Sunday: "Sunday",
      Monday: "Monday",
      Tuesday: "Tuesday",
      Wednesday: "Wednesday",
      Thursday: "Thursday",
      Friday: "Friday",
      Saturday: "Saturday"
    },
    doctor: "Professor",
    day: "Day",
    time: "Time",
    courseStatus: "Status",
    regEnabled: "Registration Open",
    regDisabled: "Registration Closed",
    downloadTimetable: "Download as Image",
    announcements: "Announcements",
    // University ID Registry
    universityIdRegistry: "University ID Registry",
    registryAccess: "Registry Access",
    uploadExcel: "Upload Excel",
    addManually: "Add Manually",
    universityIdColumn: "University ID",
    nameColumn: "Name",
    statusColumn: "Status",
    createdAtColumn: "Created At",
    usedAtColumn: "Used At",
    available: "Available",
    used: "Used",
    registryFilterAll: "All",
    filterAvailable: "Available Only",
    filterUsed: "Used Only",
    searchPlaceholder: "Search by University ID...",
    uploadSuccess: "File uploaded successfully",
    recordsAdded: "records added",
    recordsSkipped: "records skipped",
    duplicateWarning: "Duplicate IDs were skipped",
    invalidFormat: "Invalid file format. Use Excel file (.xlsx)",
    exportAll: "Export All",
    exportAvailable: "Export Available",
    exportUsed: "Export Used",
    idNotRegistered: "University ID is not registered. Please contact administration.",
    idAlreadyUsed: "This university ID has already been used and cannot be registered again.",
    cannotEditUsedId: "Cannot edit a used university ID",
    addStudent: "Add Student",
    editStudent: "Edit Student",
    deleteStudent: "Delete from Registry",
    confirmDelete: "Are you sure you want to delete this record?",
    totalRecords: "Total Records",
    availableRecords: "Available Records",
    usedRecords: "Used Records",
    // Exams & Transcript
    exams: "Exams",
    transcript: "Transcript",
    transcripts: "Transcripts",
    examManagement: "Exam Management",
    newExam: "New Exam",
    examTitle: "Exam Title",
    totalMarks: "Total Marks",
    startsAt: "Starts At",
    endsAt: "Ends At",
    published: "Published",
    draft: "Draft",
    resultsReleased: "Results Released",
    releaseSemester: "Release Semester",
    semesterApproval: "Semester Approval",
    startExam: "Start Exam",
    submitExam: "Submit Exam",
    viewResults: "View Results",
    pendingResults: "Pending Results",
    noExams: "No exams",
    exportPDF: "Export PDF",
    cumulativeGPA: "Cumulative GPA",
    attendance: "Attendance",
    participation: "Participation",
    duplicateQuestion: "Duplicate Question",
    draftSaved: "Draft Saved",
    saveExam: "Save Exam",
    exportGrades: "Export Grades",
    exportAllExams: "Export All Exams",
    exportThisExam: "Export This Exam",
    studentSearch: "Search Student",
    examsTaken: "Exams Taken",
    score: "Score",
    allFieldsRequired: "All fields are required",
    totalMustBe50: "Total must be exactly 50",
    confirmDeleteExam: "Delete this exam?",
    confirmSubmitResults: "Release results? This cannot be undone.",
    examSaved: "Exam saved",
    questionText: "Question Text",
    marks: "Marks",
    addOption: "Add Option",
    selectCourse: "Select Course",
    selectSemester: "Select Semester",
    selectStudent: "Select Student"
  },
  FR: {
    dir: 'ltr',
    regionalCenter: 'Premier Centre Régional',
    login: 'Connexion',
    signup: 'S\'inscrire',
    email: 'Email',
    password: 'Mot de passe',
    fullName: 'Nom Complet',
    universityId: 'ID Universitaire',
    phone: 'Téléphone',
    major: 'Spécialisation',
    logout: 'Déconnexion',
    dashboard: 'Tableau de bord',
    registration: 'Inscription',
    myCourses: 'Mes cours',
    profile: 'Profil',
    courses: 'Cours',
    students: 'Étudiants',
    enrollments: 'Inscriptions',
    settings: 'Paramètres',
    save: 'Enregistrer',
    cancel: 'Annuler',
    addCourse: 'Ajouter un cours',
    search: 'Chercher...',
    noData: 'Aucune donnée',
    welcome: 'Bienvenue',
    adminPanel: 'Panneau d\'administration',
    studentPanel: 'Portail étudiant',
    darkMode: "Mode Sombre",
    lightMode: "Mode Clair",
    accountDisabledMsg: "Votre compte est temporairement fermé, veuillez contacter la direction",
    majorList: {
      islamic_studies: "Études Islamiques",
      business_admin: "Administration des Affaires",
      media_pr: "Médias et RP"
    },
    days: {
      Sunday: "Dimanche",
      Monday: "Lundi",
      Tuesday: "Mardi",
      Wednesday: "Mercredi",
      Thursday: "Jeudi",
      Friday: "Vendredi",
      Saturday: "Samedi"
    }
  },
  RU: {
    dir: 'ltr',
    regionalCenter: 'Первый региональный центр',
    login: 'Авторизоваться',
    signup: 'Зарегистрироваться',
    email: 'Электронная почта',
    password: 'Пароль',
    fullName: 'Полное имя',
    universityId: 'Университетский номер',
    phone: 'Номер телефона',
    major: 'Специальность',
    logout: 'Выйти',
    dashboard: 'Панель управления',
    registration: 'Регистрация',
    myCourses: 'Мои курсы',
    profile: 'Профиль',
    courses: 'Курсы',
    students: 'Студенты',
    enrollments: 'Регистрации',
    settings: 'Настройки',
    save: 'Сохранить',
    cancel: 'Отмена',
    addCourse: 'Добавить курс',
    search: 'Поиск...',
    noData: 'Нет данных',
    welcome: 'Добро пожаловать',
    adminPanel: 'Панель администратора',
    studentPanel: 'Студенческий портал',
    darkMode: "Темный режим",
    lightMode: "Светлый режим",
    accountDisabledMsg: "Ваша учетная запись временно закрыта, пожалуйста, свяжитесь с руководством",
    majorList: {
      islamic_studies: "Исламские исследования",
      business_admin: "Бизнес-администрирование",
      media_pr: "СМИ и PR"
    },
    days: {
      Sunday: "Воскресенье",
      Monday: "Понедельник",
      Tuesday: "Вторник",
      Wednesday: "Среда",
      Thursday: "Четверг",
      Friday: "Пятница",
      Saturday: "Суббота"
    }
  }
};